### ISSUE TITLE
You should be grateful

### ISSUE THREAD

**Issue by dumplingbao** [jwilber/roughViz#4]
https://github.com/timqian/chart.xkcd

**Comment by jwilber** [comment]
Yeah, that's a cool library.
That library achieves its hand-drawness via svg filters. It is also themed along xkcd.
This one is built on `rough.js`, so the hand-drawness is parameterized. It has no specific theme.

There are plenty of other hand-drawn charting options, as well as xkcd options. 

That said, I think your issue is clearly more meant to be an insult? I'll give you the benefit of the doubt, though. What should I be grateful for?

 Looking forward to your response @dumplingbao :)

**Comment by jwilber** [comment]
Gonna go ahead and close this now since (what a surprise!) it seems like you're not quite working up the confidence to reply @dumplingbao. If you ever need help with your confidence [I found something just for you](https://www.parents.com/toddlers-preschoolers/development/fear/teach-your-kid-confidence-from-birth/).

**Comment by dumplingbao** [comment]
呵呵
